# Generated by Django 2.1.1 on 2019-02-08 15:33

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190208_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
