# Generated by Django 2.1.1 on 2019-02-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_read_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='read_num',
        ),
    ]
